############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Mentor"
url = "about/"
weight = 2

[[main]]
name = "Resources"
url = "elements/"
weight = 3

[[main]]
weight = 4
name = "Blog"
url = "blog/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Resources"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4